### ISSUE TITLE
Does this plan on getting updated?

### ISSUE THREAD

**Issue by Bluemethyst** [riolubruh/FriendInvites#1]
This is not working for me and im just wondering if you plan to bring this forward to work with latest versions of betterdiscord?

**Comment by riolubruh** [comment]
I'm not even sure myself. I figured that nobody was using it anyways so there was no point in updating it, so I just put the "do what the fuck you want to public license" on it which basically allows anyone to freely use and modify the code as they please, and left it as is. Furthermore, there are other plugins out there that provide the same/similar functionality to this one so it's not like it's really filling a gap in the BD plugin scene or anything.

**Comment by riolubruh** [comment]
Archived: Discord is finally adding this feature
